import { Video, User, UserRole, Comment } from './types';

export const MOCK_VIDEOS: Video[] = [
  {
    id: 'v1',
    title: 'The Future of AI in 2025',
    description: 'An in-depth look at how generative AI will reshape industries.',
    thumbnail: 'https://picsum.photos/seed/ai2025/640/360',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    author: 'TechDaily',
    views: 12500,
    likes: 340,
    uploadDate: '2023-10-15',
    category: 'Technology',
    tags: ['ai', 'future', 'tech'],
  },
  {
    id: 'v2',
    title: 'Minimalist Home Setup Tour',
    description: 'Check out my clean desk setup for maximum productivity.',
    thumbnail: 'https://picsum.photos/seed/setup/640/360',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    author: 'LifestyleJane',
    views: 8900,
    likes: 560,
    uploadDate: '2023-10-20',
    category: 'Lifestyle',
    tags: ['home', 'minimalism', 'setup'],
  },
  {
    id: 'v3',
    title: 'Top 10 Coding Tips for React',
    description: 'Master React hooks and components with these pro tips.',
    thumbnail: 'https://picsum.photos/seed/react/640/360',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    author: 'CodeMaster',
    views: 45000,
    likes: 1200,
    uploadDate: '2023-09-05',
    category: 'Technology',
    tags: ['coding', 'react', 'javascript'],
  },
  {
    id: 'v4',
    title: 'Healthy Morning Routine',
    description: 'Start your day right with these healthy habits.',
    thumbnail: 'https://picsum.photos/seed/morning/640/360',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    author: 'WellnessHub',
    views: 3200,
    likes: 150,
    uploadDate: '2023-11-01',
    category: 'Health',
    tags: ['health', 'routine', 'morning'],
  },
  {
    id: 'v5',
    title: 'Exploring the Alps',
    description: 'Hiking through the breathtaking mountains of Switzerland.',
    thumbnail: 'https://picsum.photos/seed/alps/640/360',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    author: 'TravelMore',
    views: 56000,
    likes: 2300,
    uploadDate: '2023-08-12',
    category: 'Travel',
    tags: ['travel', 'nature', 'hiking'],
  },
  {
    id: 'v6',
    title: 'Python for Data Science',
    description: 'Introduction to Pandas and Scikit-Learn.',
    thumbnail: 'https://picsum.photos/seed/python/640/360',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    author: 'DataWizard',
    views: 15000,
    likes: 400,
    uploadDate: '2023-10-01',
    category: 'Technology',
    tags: ['python', 'data', 'coding'],
  },
   {
    id: 'v7',
    title: 'Easy Pasta Recipe',
    description: 'Cook a delicious meal in under 15 minutes.',
    thumbnail: 'https://picsum.photos/seed/pasta/640/360',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    author: 'ChefMario',
    views: 21000,
    likes: 800,
    uploadDate: '2023-10-25',
    category: 'Food',
    tags: ['cooking', 'food', 'recipe'],
  },
];

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    username: 'demo_user',
    avatar: 'https://picsum.photos/seed/u1/100/100',
    role: UserRole.USER,
    history: ['v1', 'v3'],
    favorites: ['v3'],
    likes: ['v1'],
  },
  {
    id: 'u2',
    username: 'admin_user',
    avatar: 'https://picsum.photos/seed/u2/100/100',
    role: UserRole.ADMIN,
    history: [],
    favorites: [],
    likes: [],
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'c1',
    videoId: 'v1',
    username: 'Alice',
    avatar: 'https://picsum.photos/seed/alice/50/50',
    content: 'Great explanation of the concepts!',
    timestamp: '2 hours ago',
  },
  {
    id: 'c2',
    videoId: 'v1',
    username: 'Bob',
    avatar: 'https://picsum.photos/seed/bob/50/50',
    content: 'I disagree with the second point, but overall good video.',
    timestamp: '1 day ago',
  },
];
